### ISSUE TITLE
CAR ACCIDENT 

### ISSUE THREAD

**Issue by Hariprasathyada** [KolathuruBhaskar/naan-mudhalvan-AI-PROJECT#1]
UPLOAD ARE DISABLED

**Comment by KolathuruBhaskar** [comment]
I already submitted my AI project in Naan Mudhalvan. In GitHub my project
name was (Voice Interaction using ai)

**Comment by KolathuruBhaskar** [comment]
[Presentation. For AI project Naan Mudhalvan.pptx](https://github.com/KolathuruBhaskar/naan-mudhalvan-AI-PROJECT/files/15075981/Presentation.For.AI.project.Naan.Mudhalvan.pptx)
